### ISSUE TITLE
Error in _sock_state_cb under Windows 10

### ISSUE THREAD

**Issue by ak545** [dmippolitov/pydnsbl#12]
Hello!

Under Windows 10 x64 (build 2004) and Python 3.8.1 x64, an error appears:

```
From cffi callback <function _sock_state_cb at 0x000002A1125D0310>:
Traceback (most recent call last):
  File "C:\Python\Python38\lib\site-packages\pycares\__init__.py", line 91, in _sock_state_cb
    sock_state_cb(socket_fd, readable, writable)
  File "C:\Python\Python38\lib\site-packages\aiodns\__init__.py", line 104, in _sock_state_cb
    self.loop.add_reader(fd, self._handle_event, fd, READ)
  File "C:\Python\Python38\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```

For Python 3.8 for Windows and above is required:

```
import sys
import aiodns
import asyncio

if sys.platform == 'win32' and sys.version_info >= (3, 8):
     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

# Done...

```
https://docs.python.org/3.8/library/asyncio-platforms.html#asyncio-platform-support

Best Regards,
Andrey Klimov

**Comment by dmippolitov** [comment]
Thank you! fixed in 1.0.5
